version: "3.9"
services:
  web:
    build: ./src/.
    ports:
      - "5000:80"
  rabittmq:
    image: "rabbitmq:3-management"
    container_name: 'rabbitmq'
    ports:
      - "8080:15672"
      - "5672:5672"
    environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=password
