version: "3.9"
services:
  orderservice:
    build: ./src/OrderService/.
    ports:
      - "5001:80"
    depends_on:
      "rabbitmq" :
        condition: service_healthy
  warehouseservice:
    build: ./src/WarehouseService/.
    ports:
      - "5005:80"
    depends_on:
      "rabbitmq" :
        condition: service_healthy
  ui:
    build: ./src/myeshop/.
    ports:
      - "5002:80"
    depends_on:
      - orderservice
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "8080:15672"
      - "5672:5672"
    environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10
  order_mssql_db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "order_mssql_db"
    ports:
      - "1433:1433"
    volumes:
      - /var/opt/mssql
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=S3cur3P@ssW0rd!
volumes:
  dbfolder:
    external: true

